# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitswitch < Formula
  desc "Manage multiple git profiles locally"
  homepage "https://github.com/aksisonline/gitswitch"
  version "0.2.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aksisonline/gitswitch/releases/download/v0.2.5/gitswitch-darwin-amd64"
      sha256 "057a1d30f0bad74ee5a7c32e610ac954a8fd03e2e6f6da1ff2f0034c95b046a4"

      define_method(:install) do
        bin.install "gitswitch-darwin-amd64" => "gitswitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aksisonline/gitswitch/releases/download/v0.2.5/gitswitch-darwin-arm64"
      sha256 "b0a8a0210c95921f28e60d8b15d296b1a96c0b3627344fd98366b64be87161ea"

      define_method(:install) do
        bin.install "gitswitch-darwin-arm64" => "gitswitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aksisonline/gitswitch/releases/download/v0.2.5/gitswitch-linux-amd64"
      sha256 "31b31c3e98cf56bb4c51df6c48679ff39ff770922ae04e840260290cbccf9605"
      define_method(:install) do
        bin.install "gitswitch-linux-amd64" => "gitswitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aksisonline/gitswitch/releases/download/v0.2.5/gitswitch-linux-arm64"
      sha256 "8660102e2580689b4fb51c749fd1a5deb8aebf742c2188e8d13c144f4d040bcc"
      define_method(:install) do
        bin.install "gitswitch-linux-arm64" => "gitswitch"
      end
    end
  end

  test do
    system "#{bin}/gitswitch", "current"
  end
end
